authors:
  dzamo:
    name: Daniel Oscar Zamo
    description: Student
    avatar: https://avatars.githubusercontent.com/u/5117018?v=4
    url: https://github.com/danielzamo
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/932156
    url: https://github.com/squidfunk
  alexvoss:
    name: Alex Voss
    description: Solutions Architect
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss
  katharinalisalin:
    name: Kathi
    description: Communications
    avatar: https://avatars.githubusercontent.com/u/105352741
    url: https://github.com/katharinalisalin
